# Generated by Django 3.1.2 on 2021-10-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20211028_1509'),
        ('shops', '0004_auto_20211028_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTemplate',
        ),
    ]
